file = file_text_open_read("controls.cfl");
rk_= file_text_read_real(file);
file_text_readln(file);
//rk2= file_text_read_real(file);
file_text_readln(file);
lk_ = file_text_read_real(file);
file_text_readln(file);
//lk2 = file_text_read_real(file);
file_text_readln(file);
uk_ = file_text_read_real(file);
file_text_readln(file);
//uk2 = file_text_read_real(file);
file_text_readln(file);
dk_ = file_text_read_real(file);
file_text_readln(file);
//dk2 = file_text_read_real(file);
file_text_readln(file);
jump_ = file_text_read_real(file);
file_text_readln(file);
shoot_ = file_text_read_real(file);
file_text_readln(file);
use_ = file_text_read_real(file);
file_text_readln(file);
pause_button = file_text_read_real(file);
file_text_readln(file);
sprint_ = file_text_read_real(file);
file_text_readln(file);
crouch_ = file_text_read_real(file);
file_text_readln(file);
inventory_ = file_text_read_real(file);
file_text_readln(file);
file_text_close(file);
